name: Docker Images to EB

on:
  push:
    branches: [ "master" ]

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Build test docker image
      run: docker build -t bratzzie/multi-client-test -f ./client/Dockerfile.dev ./client
    - name: Run tests
      run: docker run -e CI=true bratzzie/multi-client-test npm run test -- --coverage
