name: Docker Images to EB

on:
  push:
    branches: [ "master" ]

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Build test docker image
      run: docker build -t bratzzie/multi-client-test -f ./client/Dockerfile.dev ./client
    - name: Run tests
      run: docker run -e CI=true bratzzie/multi-client-test npm run test -- --coverage

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Build the Docker images
    - run: |-
        docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - run: docker build -t bratzzie/multi-client -f ./client/Dockerfile.dev ./client
    - run: docker build -t bratzzie/multi-server -f ./server/Dockerfile.dev ./server
    - run: docker build -t bratzzie/multi-worker -f ./worker/Dockerfile.dev ./worker
    - run: docker build -t bratzzie/multi-nginx -f ./nginx/Dockerfile.dev ./nginx
    - run: docker push bratzzie/multi-client
    - run: docker push bratzzie/multi-server
    - run: docker push bratzzie/multi-worker
    - run: docker push bratzzie/multi-nginx
  
